---
- hosts: all
  gather_facts: false
  tasks:

    - name: Output the source URI to json 
      copy: 
        dest: /home/blessed/Downloads/Intent-Driven-Closed-Loops--main/basic_three_node/files/sink_api.json
        content: "{'output_sink_URI': '{{link_for_download}}'}"

  # set the network attributes

    #   # command: "cat {{ text_file_artifact }}"
    #   # register: text_file_contents

    # - name: Set text file attribute
      # set_stats:
      #   data:
      #     my_text_file_attribute: "{{ text_file_contents.stdout }}"

    - name: See what's in that linked JSON file
      command: "cat {{ json_file_artifact }}"
      register: json_file_contents

    # - name: Set JSON file attribute
    #   set_stats:
    #     data:
    #       my_json_file_attribute: "{{ json_file_contents.stdout }}"
    # - uri: 
    #     url: "{{ link_for_download }}"
    #     method: POST
    #     # return_content: yes
    #     # HEADER_Content-Type: "application/json"
    #     body: "{{ json_file_contents.stdout }}"
    #     body_format: json




    - name: Create Dockerfile
      copy:
        dest: /home/blessed/Downloads/Intent-Driven-Closed-Loops--main/basic_three_node/playbooks/Dockerfile
        content: > 
          #Image for source node

          FROM ubuntu 
          
          # MAINTAINER gudablessed@gmail.com 

          RUN apt-get update 

          RUN apt-get install -y curl

          RUN curl  {{link_for_download}}

      


    - name: build container image
      docker_image:
        name: sinkcontainer:v1.0
        source: build
        build:
          path: /home/blessed/Downloads/Intent-Driven-Closed-Loops--main/basic_three_node/playbooks/
        state: present


    - name: archive container image as a tarball
      docker_image:
        name: sinkcontainer:v1.0
        archive_path: /home/blessed/Downloads/Intent-Driven-Closed-Loops--main/basic_three_node/playbooks/sinkcontainer_v1_0.tar
        source: pull
        state: present

    - name: load container from tarball
      docker_image:
        name: sinkcontainer:v1.0
        load_path: /home/blessed/Downloads/Intent-Driven-Closed-Loops--main/basic_three_node/playbooks/sinkcontainer_v1_0.tar
        state: present
        source: load